name: sync-docker

on:
  workflow_dispatch

permissions:
  contents: read    # This is required for actions/checkout
  actions: read     # for read job status
  packages: write

jobs:
  sync:
    name: pull and push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: push docker image
        run: |
          docker pull xprobe/xinference:v0.10.1
          docker tag xprobe/xinference:v0.10.1 ghcr.io/abel-liu/xinference:v0.10.1
          docker push ghcr.io/abel-liu/xinference:v0.10.1
          
